//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociaciones
    {
        public Asociaciones()
        {
            this.Clubes = new HashSet<Clubes>();
            this.Torneos = new HashSet<Torneos>();
            this.UsuariosAsociaciones = new HashSet<UsuariosAsociaciones>();
            this.JugadoresPases = new HashSet<JugadoresPases>();
            this.JugadoresPases1 = new HashSet<JugadoresPases>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public int idFederacion { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string coordenadas { get; set; }
        public bool activo { get; set; }
        public string logo { get; set; }
    
        public virtual Federaciones Federaciones { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual ICollection<Clubes> Clubes { get; set; }
        public virtual ICollection<Torneos> Torneos { get; set; }
        public virtual ICollection<UsuariosAsociaciones> UsuariosAsociaciones { get; set; }
        public virtual ICollection<JugadoresPases> JugadoresPases { get; set; }
        public virtual ICollection<JugadoresPases> JugadoresPases1 { get; set; }
    }
}
