//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clubes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clubes()
        {
            this.FixturesPartidos = new HashSet<FixturesPartidos>();
            this.FixturesPartidos1 = new HashSet<FixturesPartidos>();
            this.JugadoresPases = new HashSet<JugadoresPases>();
            this.JugadoresPases1 = new HashSet<JugadoresPases>();
            this.Jugadores = new HashSet<Jugadores>();
        }
    
        public int id { get; set; }
        public int idAsociacion { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string coordenadas { get; set; }
        public bool activo { get; set; }
        public string logo { get; set; }
    
        public virtual Asociaciones Asociaciones { get; set; }
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixturesPartidos> FixturesPartidos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixturesPartidos> FixturesPartidos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugadores> Jugadores { get; set; }
    }
}
