//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeportesEntities : DbContext
    {
        public DeportesEntities()
            : base("name=DeportesEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asociaciones> Asociaciones { get; set; }
        public virtual DbSet<Categorias> Categorias { get; set; }
        public virtual DbSet<Clubes> Clubes { get; set; }
        public virtual DbSet<DNI> DNI { get; set; }
        public virtual DbSet<Equipos> Equipos { get; set; }
        public virtual DbSet<Especialidades> Especialidades { get; set; }
        public virtual DbSet<Federaciones> Federaciones { get; set; }
        public virtual DbSet<Fixtures> Fixtures { get; set; }
        public virtual DbSet<FixturesPartidos> FixturesPartidos { get; set; }
        public virtual DbSet<Jueces> Jueces { get; set; }
        public virtual DbSet<JugadoresCategorias> JugadoresCategorias { get; set; }
        public virtual DbSet<JugadoresHabilitaciones> JugadoresHabilitaciones { get; set; }
        public virtual DbSet<JugadoresSolicitudesCarnets> JugadoresSolicitudesCarnets { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Torneos> Torneos { get; set; }
        public virtual DbSet<TorneosActividades> TorneosActividades { get; set; }
        public virtual DbSet<TorneosEquipos> TorneosEquipos { get; set; }
        public virtual DbSet<TorneosEspecialidades> TorneosEspecialidades { get; set; }
        public virtual DbSet<TorneosPartidos> TorneosPartidos { get; set; }
        public virtual DbSet<TorneosZonas> TorneosZonas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosAsociaciones> UsuariosAsociaciones { get; set; }
        public virtual DbSet<UsuariosFederaciones> UsuariosFederaciones { get; set; }
        public virtual DbSet<UsuariosRoles> UsuariosRoles { get; set; }
        public virtual DbSet<JugadoresPases> JugadoresPases { get; set; }
        public virtual DbSet<JugadoresPasesEstados> JugadoresPasesEstados { get; set; }
        public virtual DbSet<PasesEstados> PasesEstados { get; set; }
        public virtual DbSet<JugadoresPenalizaciones> JugadoresPenalizaciones { get; set; }
        public virtual DbSet<JugadoresPenalizacionesEstados> JugadoresPenalizacionesEstados { get; set; }
        public virtual DbSet<PenalizacionesEstados> PenalizacionesEstados { get; set; }
        public virtual DbSet<Noticias> Noticias { get; set; }
        public virtual DbSet<habilitaciones> habilitaciones { get; set; }
        public virtual DbSet<tmbcarnet> tmbcarnet { get; set; }
        public virtual DbSet<ExportacionExel> ExportacionExel { get; set; }
        public virtual DbSet<Campeones> Campeones { get; set; }
        public virtual DbSet<Jugadores> Jugadores { get; set; }
        public virtual DbSet<JugadoresEliminados> JugadoresEliminados { get; set; }
        public virtual DbSet<JugadoresHistorial> JugadoresHistorial { get; set; }
    
        public virtual ObjectResult<uspInformes_CarnetsNoEntregados_Result> uspInformes_CarnetsNoEntregados(Nullable<System.DateTime> fechaSolicitudDesde, Nullable<System.DateTime> fechaSolicitudHasta, string filtro, Nullable<int> idUsuario)
        {
            var fechaSolicitudDesdeParameter = fechaSolicitudDesde.HasValue ?
                new ObjectParameter("fechaSolicitudDesde", fechaSolicitudDesde) :
                new ObjectParameter("fechaSolicitudDesde", typeof(System.DateTime));
    
            var fechaSolicitudHastaParameter = fechaSolicitudHasta.HasValue ?
                new ObjectParameter("fechaSolicitudHasta", fechaSolicitudHasta) :
                new ObjectParameter("fechaSolicitudHasta", typeof(System.DateTime));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspInformes_CarnetsNoEntregados_Result>("uspInformes_CarnetsNoEntregados", fechaSolicitudDesdeParameter, fechaSolicitudHastaParameter, filtroParameter, idUsuarioParameter);
        }
    
        public virtual ObjectResult<uspInformes_Pases_Result> uspInformes_Pases(Nullable<int> idUsuario, string filtro, Nullable<System.DateTime> fechaDesde, Nullable<System.DateTime> fechaHasta, Nullable<int> idFederacion, Nullable<int> idAsociacion)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            var fechaDesdeParameter = fechaDesde.HasValue ?
                new ObjectParameter("fechaDesde", fechaDesde) :
                new ObjectParameter("fechaDesde", typeof(System.DateTime));
    
            var fechaHastaParameter = fechaHasta.HasValue ?
                new ObjectParameter("fechaHasta", fechaHasta) :
                new ObjectParameter("fechaHasta", typeof(System.DateTime));
    
            var idFederacionParameter = idFederacion.HasValue ?
                new ObjectParameter("idFederacion", idFederacion) :
                new ObjectParameter("idFederacion", typeof(int));
    
            var idAsociacionParameter = idAsociacion.HasValue ?
                new ObjectParameter("idAsociacion", idAsociacion) :
                new ObjectParameter("idAsociacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspInformes_Pases_Result>("uspInformes_Pases", idUsuarioParameter, filtroParameter, fechaDesdeParameter, fechaHastaParameter, idFederacionParameter, idAsociacionParameter);
        }
    
        public virtual ObjectResult<uspInformes_JugadoresHabilitados_Result> uspInformes_JugadoresHabilitados(string filtro, Nullable<int> idUsuario, Nullable<int> idFederacion, Nullable<int> idAsociacion, Nullable<int> idClub, Nullable<int> estampilla)
        {
            var filtroParameter = filtro != null ?
                new ObjectParameter("filtro", filtro) :
                new ObjectParameter("filtro", typeof(string));
    
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            var idFederacionParameter = idFederacion.HasValue ?
                new ObjectParameter("idFederacion", idFederacion) :
                new ObjectParameter("idFederacion", typeof(int));
    
            var idAsociacionParameter = idAsociacion.HasValue ?
                new ObjectParameter("idAsociacion", idAsociacion) :
                new ObjectParameter("idAsociacion", typeof(int));
    
            var idClubParameter = idClub.HasValue ?
                new ObjectParameter("idClub", idClub) :
                new ObjectParameter("idClub", typeof(int));
    
            var estampillaParameter = estampilla.HasValue ?
                new ObjectParameter("estampilla", estampilla) :
                new ObjectParameter("estampilla", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<uspInformes_JugadoresHabilitados_Result>("uspInformes_JugadoresHabilitados", filtroParameter, idUsuarioParameter, idFederacionParameter, idAsociacionParameter, idClubParameter, estampillaParameter);
        }
    }
}
