//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNI
    {
        public int dni1 { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha { get; set; }
        public decimal clubid { get; set; }
        public decimal categoriaid { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string ciudad { get; set; }
        public string provincia { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<System.DateTime> fechabaja { get; set; }
        public string habilitadoanual { get; set; }
        public Nullable<decimal> habilitacionnumero { get; set; }
        public Nullable<short> CarnetSolicita { get; set; }
        public Nullable<System.DateTime> CarnetFechaSolicita { get; set; }
        public Nullable<short> CarnetEntrego { get; set; }
        public Nullable<System.DateTime> CarnetFechaEntrega { get; set; }
        public Nullable<System.DateTime> fechaHabilitacion { get; set; }
        public Nullable<System.DateTime> fechaInHabilitacion { get; set; }
    }
}
