//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Federaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Federaciones()
        {
            this.Asociaciones = new HashSet<Asociaciones>();
            this.Torneos = new HashSet<Torneos>();
            this.UsuariosFederaciones = new HashSet<UsuariosFederaciones>();
            this.JugadoresPases = new HashSet<JugadoresPases>();
            this.JugadoresPases1 = new HashSet<JugadoresPases>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string telefono { get; set; }
        public string fax { get; set; }
        public string mail { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string coordenadas { get; set; }
        public bool activo { get; set; }
        public string logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asociaciones> Asociaciones { get; set; }
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneos> Torneos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosFederaciones> UsuariosFederaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases1 { get; set; }
    }
}
