//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixturesPartidos
    {
        public int id { get; set; }
        public int idFixture { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public int nroPartido { get; set; }
        public Nullable<int> idClub1 { get; set; }
        public Nullable<int> tantosClub1 { get; set; }
        public Nullable<int> idClub2 { get; set; }
        public Nullable<int> tantosClub2 { get; set; }
        public string cancha { get; set; }
        public Nullable<int> idJuez { get; set; }
        public Nullable<bool> iidClub1Ganador { get; set; }
        public Nullable<int> idClub1NroPartido { get; set; }
        public Nullable<bool> idClub2Ganador { get; set; }
        public Nullable<int> idClub2NroPartido { get; set; }
        public Nullable<int> idRonda { get; set; }
        public string ronda { get; set; }
    
        public virtual Clubes Clubes { get; set; }
        public virtual Clubes Clubes1 { get; set; }
        public virtual Fixtures Fixtures { get; set; }
        public virtual Jueces Jueces { get; set; }
    }
}
