//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class habilitaciones1
    {
        public int id { get; set; }
        public int numero { get; set; }
        public System.DateTime fechaHabilitacion { get; set; }
        public System.DateTime fechaInhabilitacion { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idJugador { get; set; }
    }
}
