//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresSolicitudesCarnets
    {
        public int id { get; set; }
        public int idJugador { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public Nullable<int> idUsuarioEntrega { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string motivo { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
        public virtual Jugadores Jugadores { get; set; }
    }
}
