//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresPenalizaciones
    {
        public JugadoresPenalizaciones()
        {
            this.JugadoresPenalizacionesEstados = new HashSet<JugadoresPenalizacionesEstados>();
        }
    
        public int id { get; set; }
        public int idJugador { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public int dias { get; set; }
        public bool aprobadoPorConfederacion { get; set; }
        public bool aprobadoPorFederacion { get; set; }
        public int idUsuario { get; set; }
        public string motivos { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int idPenalizacionEstado { get; set; }
        public System.DateTime fechaFin { get; set; }
        public bool requiereAprobacionFederacion { get; set; }
    
        public virtual PenalizacionesEstados PenalizacionesEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<JugadoresPenalizacionesEstados> JugadoresPenalizacionesEstados { get; set; }
        public virtual Jugadores Jugadores { get; set; }
    }
}
