//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresEliminados
    {
        public int codigo { get; set; }
        public int id { get; set; }
        public long DNI { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int idClub { get; set; }
        public int idCategoria { get; set; }
        public string direccion { get; set; }
        public string telefonoFijo { get; set; }
        public string celular { get; set; }
        public string mail { get; set; }
        public string localidad { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string foto { get; set; }
        public Nullable<bool> solicitaCarnet { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
        public Nullable<int> usuarioEliminacion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
