//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresPases
    {
        public JugadoresPases()
        {
            this.JugadoresPasesEstados = new HashSet<JugadoresPasesEstados>();
        }
    
        public int id { get; set; }
        public int idJugador { get; set; }
        public System.DateTime fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaPase { get; set; }
        public int idUsuarioSolicitud { get; set; }
        public int idClubOrigen { get; set; }
        public int idAsociacionOrigen { get; set; }
        public int idFederacionOrigen { get; set; }
        public int idClubDestino { get; set; }
        public int idAsociacionDestino { get; set; }
        public int idFederacionDestino { get; set; }
        public string tipoPase { get; set; }
        public int idPaseEstado { get; set; }
        public string motivosRechazo { get; set; }
        public Nullable<int> idCategoria { get; set; }
    
        public virtual Asociaciones Asociaciones { get; set; }
        public virtual Asociaciones Asociaciones1 { get; set; }
        public virtual Clubes Clubes { get; set; }
        public virtual Clubes Clubes1 { get; set; }
        public virtual Federaciones Federaciones { get; set; }
        public virtual Federaciones Federaciones1 { get; set; }
        public virtual PasesEstados PasesEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<JugadoresPasesEstados> JugadoresPasesEstados { get; set; }
        public virtual Jugadores Jugadores { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Categorias Categorias1 { get; set; }
    }
}
