//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresPasesEstados
    {
        public int id { get; set; }
        public int idJugadorPase { get; set; }
        public System.DateTime fecha { get; set; }
        public int idPaseEstado { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> idAsociacion { get; set; }
        public Nullable<int> idFederacion { get; set; }
        public string comentarios { get; set; }
    
        public virtual JugadoresPases JugadoresPases { get; set; }
        public virtual PasesEstados PasesEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
