//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresPenalizacionesEstados
    {
        public int id { get; set; }
        public int idJugadorPenalizacion { get; set; }
        public int idPenalizacionEstado { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public int dias { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaFin { get; set; }
        public string observaciones { get; set; }
    
        public virtual JugadoresPenalizaciones JugadoresPenalizaciones { get; set; }
        public virtual PenalizacionesEstados PenalizacionesEstados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
