//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresCategorias
    {
        public int id { get; set; }
        public int idJugador { get; set; }
        public int idCategoria { get; set; }
        public System.DateTime fecha { get; set; }
        public int idUsuario { get; set; }
        public System.DateTime fechaCreacion { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual Jugadores Jugadores { get; set; }
    }
}
