//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugadores()
        {
            this.JugadoresCategorias = new HashSet<JugadoresCategorias>();
            this.JugadoresHabilitaciones = new HashSet<JugadoresHabilitaciones>();
            this.JugadoresPases = new HashSet<JugadoresPases>();
            this.JugadoresPenalizaciones = new HashSet<JugadoresPenalizaciones>();
            this.JugadoresSolicitudesCarnets = new HashSet<JugadoresSolicitudesCarnets>();
            this.JugadoresHistorial = new HashSet<JugadoresHistorial>();
        }
    
        public int id { get; set; }
        public long DNI { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int idClub { get; set; }
        public int idCategoria { get; set; }
        public string direccion { get; set; }
        public string telefonoFijo { get; set; }
        public string celular { get; set; }
        public string mail { get; set; }
        public string localidad { get; set; }
        public Nullable<int> idLocalidad { get; set; }
        public string sexo { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string foto { get; set; }
        public Nullable<bool> solicitaCarnet { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> Puntaje { get; set; }
        public string Historial { get; set; }
        public string nroCarnet { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        public virtual Clubes Clubes { get; set; }
        public virtual Localidades Localidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresCategorias> JugadoresCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresHabilitaciones> JugadoresHabilitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPenalizaciones> JugadoresPenalizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresSolicitudesCarnets> JugadoresSolicitudesCarnets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresHistorial> JugadoresHistorial { get; set; }
    }
}
