//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localidades
    {
        public Localidades()
        {
            this.Asociaciones = new HashSet<Asociaciones>();
            this.Clubes = new HashSet<Clubes>();
            this.Federaciones = new HashSet<Federaciones>();
            this.Jugadores = new HashSet<Jugadores>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string codigoPostal { get; set; }
        public int idProvincia { get; set; }
        public bool activa { get; set; }
    
        public virtual ICollection<Asociaciones> Asociaciones { get; set; }
        public virtual ICollection<Clubes> Clubes { get; set; }
        public virtual ICollection<Federaciones> Federaciones { get; set; }
        public virtual Provincias Provincias { get; set; }
        public virtual ICollection<Jugadores> Jugadores { get; set; }
    }
}
