//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticias
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string titulo { get; set; }
        public string copete { get; set; }
        public string fotoPeque { get; set; }
        public Nullable<bool> destacada { get; set; }
        public string texto { get; set; }
        public string fotoAmplia { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
