//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasesEstados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PasesEstados()
        {
            this.JugadoresPases = new HashSet<JugadoresPases>();
            this.JugadoresPasesEstados = new HashSet<JugadoresPasesEstados>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public bool estadoInicial { get; set; }
        public bool estadoIntermedio { get; set; }
        public bool estadoFinal { get; set; }
        public string codigoInterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPasesEstados> JugadoresPasesEstados { get; set; }
    }
}
