//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.UsuariosRoles = new HashSet<UsuariosRoles>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string descripcionAmpliada { get; set; }
        public string codigoInterno { get; set; }
        public int nivel { get; set; }
        public bool administraContenido { get; set; }
        public bool administraSeguridad { get; set; }
        public bool administraConfederacion { get; set; }
    
        public virtual ICollection<UsuariosRoles> UsuariosRoles { get; set; }
    }
}
