//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorneosEquipos
    {
        public TorneosEquipos()
        {
            this.TorneosPartidos = new HashSet<TorneosPartidos>();
            this.TorneosPartidos1 = new HashSet<TorneosPartidos>();
        }
    
        public int id { get; set; }
        public int idTorneo { get; set; }
        public Nullable<int> idEquipo { get; set; }
        public string nombre { get; set; }
        public string tecnico { get; set; }
        public string delegado { get; set; }
        public string jugadores { get; set; }
        public string zona { get; set; }
        public string nombreCorto { get; set; }
        public Nullable<int> idEspecialidad { get; set; }
    
        public virtual Torneos Torneos { get; set; }
        public virtual ICollection<TorneosPartidos> TorneosPartidos { get; set; }
        public virtual ICollection<TorneosPartidos> TorneosPartidos1 { get; set; }
    }
}
