//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneos
    {
        public Torneos()
        {
            this.Fixtures = new HashSet<Fixtures>();
            this.TorneosActividades = new HashSet<TorneosActividades>();
            this.TorneosEquipos = new HashSet<TorneosEquipos>();
            this.TorneosEspecialidades = new HashSet<TorneosEspecialidades>();
            this.TorneosPartidos = new HashSet<TorneosPartidos>();
            this.TorneosZonas = new HashSet<TorneosZonas>();
        }
    
        public int id { get; set; }
        public string tipoCompeticion { get; set; }
        public System.DateTime fechaDesde { get; set; }
        public System.DateTime fechaHasta { get; set; }
        public Nullable<int> idFederacion { get; set; }
        public Nullable<int> idAsociacion { get; set; }
        public Nullable<int> orden { get; set; }
        public string categoria { get; set; }
        public string especialidad { get; set; }
        public string lugar { get; set; }
        public string direccion { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string telefono { get; set; }
        public Nullable<int> idUsuarioCreador { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public Nullable<bool> detalleMostrar { get; set; }
        public string detalleTitulo { get; set; }
        public string detalleDescripcion { get; set; }
        public string detalleJueces { get; set; }
        public Nullable<bool> detalleMostrarAdvertenciaDocumentacion { get; set; }
        public Nullable<bool> detalleMostrarPorgramaActividades { get; set; }
        public Nullable<bool> resultadosMostrar { get; set; }
        public string resultadosFotosFacebook { get; set; }
        public Nullable<bool> activo { get; set; }
        public string urlMaps { get; set; }
        public string resultadosTitulo { get; set; }
        public string resultadosDescripcion { get; set; }
    
        public virtual Asociaciones Asociaciones { get; set; }
        public virtual Federaciones Federaciones { get; set; }
        public virtual ICollection<Fixtures> Fixtures { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<TorneosActividades> TorneosActividades { get; set; }
        public virtual ICollection<TorneosEquipos> TorneosEquipos { get; set; }
        public virtual ICollection<TorneosEspecialidades> TorneosEspecialidades { get; set; }
        public virtual ICollection<TorneosPartidos> TorneosPartidos { get; set; }
        public virtual ICollection<TorneosZonas> TorneosZonas { get; set; }
    }
}
