//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorneosPartidos
    {
        public int id { get; set; }
        public int idTorneo { get; set; }
        public int nroPartido { get; set; }
        public int idTorneoEquipo1 { get; set; }
        public int idTorneoEquipo2 { get; set; }
        public Nullable<int> puntosEquipo1 { get; set; }
        public Nullable<int> puntosEquipo2 { get; set; }
        public string fase { get; set; }
        public Nullable<int> idEspecialidad { get; set; }
    
        public virtual Torneos Torneos { get; set; }
        public virtual TorneosEquipos TorneosEquipos { get; set; }
        public virtual TorneosEquipos TorneosEquipos1 { get; set; }
    }
}
