//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TorneosActividades
    {
        public int id { get; set; }
        public int idTorneo { get; set; }
        public System.DateTime fecha { get; set; }
        public int hora { get; set; }
        public int minutos { get; set; }
        public string descripcion { get; set; }
    
        public virtual Torneos Torneos { get; set; }
    }
}
