//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuarios()
        {
            this.JugadoresCategorias = new HashSet<JugadoresCategorias>();
            this.JugadoresHabilitaciones = new HashSet<JugadoresHabilitaciones>();
            this.JugadoresSolicitudesCarnets = new HashSet<JugadoresSolicitudesCarnets>();
            this.Torneos = new HashSet<Torneos>();
            this.UsuariosAsociaciones = new HashSet<UsuariosAsociaciones>();
            this.UsuariosFederaciones = new HashSet<UsuariosFederaciones>();
            this.UsuariosRoles = new HashSet<UsuariosRoles>();
            this.JugadoresPases = new HashSet<JugadoresPases>();
            this.JugadoresPasesEstados = new HashSet<JugadoresPasesEstados>();
            this.JugadoresPenalizaciones = new HashSet<JugadoresPenalizaciones>();
            this.JugadoresPenalizacionesEstados = new HashSet<JugadoresPenalizacionesEstados>();
            this.Noticias = new HashSet<Noticias>();
            this.JugadoresEliminados = new HashSet<JugadoresEliminados>();
            this.JugadoresHistorial = new HashSet<JugadoresHistorial>();
        }
    
        public int id { get; set; }
        public string nombreUsuario { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string mail { get; set; }
        public System.DateTime fechaAlta { get; set; }
        public bool activo { get; set; }
        public Nullable<int> idUsuarioCreador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresCategorias> JugadoresCategorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresHabilitaciones> JugadoresHabilitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresSolicitudesCarnets> JugadoresSolicitudesCarnets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Torneos> Torneos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosAsociaciones> UsuariosAsociaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosFederaciones> UsuariosFederaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosRoles> UsuariosRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPases> JugadoresPases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPasesEstados> JugadoresPasesEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPenalizaciones> JugadoresPenalizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresPenalizacionesEstados> JugadoresPenalizacionesEstados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Noticias> Noticias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresEliminados> JugadoresEliminados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresHistorial> JugadoresHistorial { get; set; }
    }
}
